# CONSTANT PARAMETERS
PERCENTAGE_INHIBITORY_WEIGHTS = 20
MAX_EPOCHS = 5
LEARNING_RATE = 5
N_PATTERNS = 1000
#.x_pattern_features = n_patterns
X_PATTERN_FEATURES = 8200  # https://pubmed.ncbi.nlm.nih.gov/2778101/
ENERGY_EXPONENT = 1
